import { randomUUID } from "node:crypto";
import { z } from "zod";
import { canUse } from "@/lib/app/account";
import { illustrate } from "@/server/ai/analysis";
import { configured } from "@/server/env";
import { getProfile } from "@/server/engine/data";
import { handle, HttpError, readBody, requireService, requireUser } from "@/server/http";
import { supabaseAdmin } from "@/server/supabase";

const Body = z.object({
  prompt: z.string().min(3).max(600),
  illustrations: z.string().max(20),
  brief: z.string().max(300),
  accent: z.string().max(7),
  count: z.number().int().min(1).max(2),
});

/* Images generated by Gemini in the ebook's illustration style (Pro) */
export async function POST(request: Request) {
  return handle(async () => {
    requireService(configured.gemini);
    const user = await requireUser();
    if (configured.supabase && !canUse("pro", (await getProfile(user.id)).plan)) {
      throw new HttpError(403, "plan_required");
    }
    const body = await readBody(request, Body);
    const images = await Promise.all(Array.from({ length: body.count }, () => illustrate(body)));

    // Without accounts (local test), the images come back inline
    if (!configured.supabase) {
      return { urls: images.map((image) => `data:${image.type};base64,${image.bytes.toString("base64")}`) };
    }
    const storage = supabaseAdmin().storage.from("images");
    const urls = await Promise.all(
      images.map(async (image) => {
        const path = `${user.id}/generated/${randomUUID()}.${image.type === "image/jpeg" ? "jpg" : "png"}`;
        const { error } = await storage.upload(path, image.bytes, { contentType: image.type });
        if (error) throw error;
        return storage.getPublicUrl(path).data.publicUrl;
      }),
    );
    return { urls };
  });
}
